const express = require("express");
const router = express.Router();
const cors = require("cors");
const nodemailer = require("nodemailer");
const { json } = require("express");

const app = express();
app.use(cors());
app.use(express.json());
app.use("/", router);
app.listen(5000, () => console.log("Server Running"));

const contactEmail = nodemailer.createTransport({
    // service: 'gmail',
    // auth: {
    //   user: "sssuvrakar@gmail.com",
    //   pass: "#####",
    // },

    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "1a2b3c4d5e6f7g",  //generated by Mailtrap
      pass: "1a2b3c4d5e6f7g" //generated by Mailtrap
    },

  });
  
  contactEmail.verify((error) => {
    if (error) {
      console.log(error);
    } else {
      console.log("Ready to Send");
    }
  });

  router.post("/contact", (req, res) => {
    const name = req.body.name;
    const email = req.body.email;
    const message = req.body.message; 
    const mail = {
      from: name,
      to: "kar.suvra@gmail.com",
      replyTo: email,
      subject: "Contact Form Submission",
      html: `<p>Name: ${name}</p>
             <p>Email: ${email}</p>
             <p>Message: ${message}</p>`,
    };

    contactEmail.sendMail(mail, (error) => {
      if (error) {
        res.json({ status: "ERROR" });
      } else {
        res.json({ status: "Message Sent" });
      }
    });
  });

  router.get("/contact", (req, res) => {
    res.json(
        
            {"name":"John", "age":30, "car":null}
        
    )
    });